---
- name: create a new user with ansible
  hosts: windows
  connection: winrm
  gather_facts: true
  
  vars_files:
    - new_users.yaml
  
  tasks:
    - name: Add User
      ansible.windows.win_user:
       - name: alice
        password: 3nterTHEm@trix
      - name: bob
        password: OrchidColl3ct0r
      - name: charlie
        password: NoClicking.StayRightHere    
        state: present
      loop: "{{ new_users }}"

